# Generated by Django 2.0.1 on 2018-10-14 09:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='content',
            field=models.TextField(default='nothing'),
        ),
        migrations.AddField(
            model_name='posts',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
