# Generated by Django 2.0.1 on 2018-10-14 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20181014_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='department',
            field=models.CharField(choices=[('CE', 'Civil Engineering'), ('AM', 'AeroModelling'), ('RO', 'Robotics'), ('CS', 'Computer Science'), ('NO', 'None')], default='NO', max_length=2),
        ),
    ]
