# Generated by Django 2.0.1 on 2018-10-14 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_posts_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('CE', 'Civil Engineering'), ('AM', 'AeroModelling'), ('RO', 'Robotics'), ('CS', 'Computer Science'), ('NO', 'None')], default='NO', max_length=2)),
                ('thumb', models.ImageField(blank=True, default='default.png', upload_to='')),
                ('slogan', models.TextField(default='slogan')),
                ('given_by', models.CharField(max_length=100)),
                ('short_des', models.TextField(default='short description')),
                ('long_des', models.TextField(default='long description')),
            ],
        ),
        migrations.RemoveField(
            model_name='posts',
            name='department',
        ),
        migrations.AddField(
            model_name='posts',
            name='title',
            field=models.CharField(default='title', max_length=100),
        ),
        migrations.AlterField(
            model_name='posts',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='department',
            field=models.CharField(choices=[('CE', 'Civil Engineering'), ('AM', 'AeroModelling'), ('RO', 'Robotics'), ('CS', 'Computer Science'), ('NO', 'None')], default='NO', max_length=2),
        ),
    ]
