# Generated by Django 2.0.1 on 2018-10-14 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20181014_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='department',
            field=models.CharField(choices=[('CE', 'Civil Engineering'), ('AM', 'AeroModelling'), ('RO', 'Robotics'), ('CS', 'Computer Science'), ('NO', 'None')], default='NO', max_length=2),
        ),
        migrations.AddField(
            model_name='posts',
            name='short_des',
            field=models.TextField(default='short description'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='content',
            field=models.TextField(default='content'),
        ),
    ]
