# Generated by Django 2.0.1 on 2018-10-15 06:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20181014_2317'),
    ]

    operations = [
        migrations.CreateModel(
            name='Components',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('person_taken', models.CharField(max_length=100)),
                ('branch', models.CharField(choices=[('CE', 'Civil Engineering'), ('CS', 'Computer Science Engineering'), ('EE', 'Electrical Engineering'), ('EL', 'Electronics Engineering'), ('ME', 'Mechanical Engineering'), ('IT', 'Information Technology'), ('NO', 'Not Mentioned')], default='NO', max_length=2)),
                ('year', models.IntegerField()),
                ('borrow_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('return_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
